EX5 = """ABIDE ABOVE ABUSE ACTOR ACUTE ADAPT ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD ALARM
ALBUM ALIKE ALLOW ALTER AMONG AMPLE ANNUAL APART APRIL AREAS ARMED ARRAY ASIAN ATLAS ATTIC AUDIO
AUNTS AVOID AWAKE BACON BADLY BASIC BASIN BASIS BATCH BEARD BEAST BEGAN BEGUN BELLY BERRY BIBLE
BIRDS BITES BLAZE BLEND BLESS BLOOM BLUES BLUNT BOARD BONUS BOOTH BOOTS BORED BOTHER BRICK BRIDE
BRUSH BUNCH BURNT BURST CABIN CANAL CANDY CANOE CARDS CARGO CARVE CEDAR CHALK CHARM CHOIR CHORD
CHOSE CIDER CIGAR CIVIL CLAMP CLASH CLERK CLIFF CLOTH COCOA COLOR COMET COMIC CORAL CORNER COUCH
COUGH CRACK CRANE CRATE CREEK CREPT CRISP CROOK CRUEL CRUSH CUBIC CURLY CURRY DAIRY DAISY DATED
DEBUT DECAY DECOR DEPOT DERBY DIARY DIRTY DITCH DIVER DOCKS DODGE DONOR DOUGH DOZED DRAIN DRANK
DRAWN DREAD DRIED DROVE DRUMS DUSTY DUTCH DWELL EAGLE EARNS EASEL EATEN EBONY EDGES EIGHT ELBOW
ELDER ELECT ELVES EMBER EMPTY ENACT ENDED ENJOY EPOCH EQUIP ERASE ESSAY ETHIC EVENT EXCEL EXILE
EXPEL FABLE FACED FADED FAINT FANCY FATAL FAVOR FEAST FENCE FERRY FETCH FEVER FEWER FIBER FIERY
FILED FILES FILMS FINCH FINDS FINER FIRED FIRST FLAKE FLAME FLANK FLASK FLEECE FLING FLINT FLIRT
FLOAT FLOCK FLOOD FLOUR FLUTE FOAMY FOCAL FOGGY FOLKS FONTS FORGE FORTS FOSSIL FOUNT FOXES FRIED
FROGS FROST FROWN FUDGE FUMES FUNDS FUNGI FUSED GAINS GAMES GAUGE GAUZE GAZED GEESE GENIE GENRE
GHOST GILLS GLADE GLARE GLAZE GLEAM GLIDE GLINT GLOOM GLORY GLOVE GNOME GOATS GOODS GOOSE GORGE
GOURD GRAIN GRAPE GRASP GRAVE GRAVY GRAZE GREED GREET GRIEF GRILL GRIME GRIND GRIPS GROAN GROIN
GROOM GROVE GRUMP GUARD GUESS GUILD GUILT GUISE GULLY GUSTS HABIT HAILS HAIRY HALLS HALVE HANDY
HARSH HASTE HATCH HAVEN HAZEL HEADS HEAPS HEARD HEATH HEDGE HEELS HEFTY HEIRS HELIX HERBS HILLS
HINGE HIPPO HOARD HOBBY HOLES HOLLY HONEY HONOR HOOKS HORNS HOTLY HOUND HOURS HOVER HUMID HUMOR
HURRY HUSKY HYENA ICING IDEAS IDIOM IDLED IGLOO IMPLY INBOX INCUR INDEX INFER INGOT INLET IRATE
IRONS IVORY JEANS JELLY JEWEL JOINS JOKES JOLLY JOUST JUDGE JUICE JUMBO KAYAK KEEPS KETTLE KHAKI
KIOSK KNACK KNEAD KNEEL KNELT KNOTS LABEL LACED LADEN LAKES LAMPS LANDS LANES LAPSE LARVA LASER
LASTS LATCH LATHE LAWNS LAYER LEAFY LEAKS LEAPS LEASH LEDGE LEGGY LEMON LENDS LENSE LEVEE LEVER
LIBEL LILAC LIMBS LIMES LINEN LINER LINKS LIONS LISTS LIVER LIVES LOAFS LOANS LOBBY LOCAL LOCKS
LODGE LOFTY LOGIC LOOMS LOOPS LOOSE LORDS LOTUS LOUSE LOVED LOWLY LOYAL LUCID LUMPY LUNAR LUNGS
LURCH LYRIC MACRO MAIZE MAKES MALLS MANGO MANOR MAPLE MARSH MASKS MASON MATES MAUVE MEADOW MEANS
MEDAL MELON MERCY MERGE MERIT MERRY MESSY METAL MIDST MILES MILKY MIMIC MINDS MINER MINTS MIRTH
MISTS MOATS MOCHA MODES MOIST MOLAR MOLDS MONKS MOODS MOONS MOOSE MOPED MORAL MOSSY MOTEL MOTHS
MOULD MOUND MOURN MOVES MOWER MUDDY MULCH MUMMY MURAL MURKY MUSHY MYRRH NAILS NAKED NAMES NAPPY
NASAL NASTY NAVAL NEEDY NERVY NESTS NEWER NICHE NIECE NIGHT NIMBLE NINTH NOBLE NODES NOISY NOMAD
NOOKS NORMS NOTCH NOTES NOUNS NUDGE NURSE NUTTY OASIS OATHS OBESE OCCUR OCHRE ODORS OFFER OLDEN
OLIVE OMEGA OMITS ONION OPENS OPERA OPTED ORBIT ORCHID ORGAN OTTER OUNCE OUTER OVALS OVENS OWING
OWNER OXIDE OZONE PACES PACKS PADDY PAGES PAINS PAINT PALES PALMS PANEL PANIC PANTS PAPER PARKS
PARTY PASTA PASTE PATCH PATHS PATIO PAUSE PAVED PEACH PEARL PEDAL PEERS PENNY PERCH PERIL PESTS
PETAL PETTY PHONE PHOTO PIANO PICKS PIECE PIERS PILES PILOT PINCH PINES PIPES PITCH PIVOT PIXEL
PIZZA PLAID PLAIT PLANK PLANS PLANT PLAZA PLEAD PLEAT PLIER PLUMB PLUME PLUMP PLUSH POACH PODIA
POEMS POETS POINT POKER POLAR POLES POLLS PONDS POOLS PORCH PORES PORTS POSED POSTS POUCH POUNDS
PRANK PRAWN PRAYS PRESS PRIED PRIME PRINT PRIOR PRISM PRIZE PROBE PRONE PRONG PROOF PROPS PROSE
PROUD PROVE PRUNE PULSE PUNCH PUPIL PUPPY PUREE PURGE PURSE QUACK QUAIL QUAKE QUART QUEST QUEUE
QUILT QUIRK QUOTA QUOTE RACED RACES RADAR RAFTS RAGED RAILS RAINY RAISE RAKES RALLY RANCH RANGE
RANKS RAPID RATIO RAVEN RAYON REACH REACT REALM REAPS REBEL RECAP REEDS REEFS REFIT REIGN REINS
RELAX RELAY REMIT RENEW RENTS REPAY REPLY RESIN RESTS RIDER RIDGE RIFLE RIGHT RIGID RINGS RINSE
RIOTS RIPEN RISEN RISKY RIVAL RIVER ROADS ROAST ROBES ROBIN ROBOT ROCKS ROCKY RODEO ROLES ROLLS
ROOFS ROOMS ROOST ROOTS ROPES ROSES ROTOR ROUGE ROUGH ROUND ROUSE ROUTE ROWDY ROYAL RUINS RULED
RULER RUMOR RUNGS RUNNY RURAL RUSTY SABLE SADLY SAFER SAILS SAINT SALAD SALES SALON SALTY SANDS
SANDY SAUCE SAUNA SAVED SAVOR SCALE SCALP SCANS SCARF SCARY SCENE SCENT SCOLD SCOOP SCOPE SCORE
SCOUT SCRAP SCREW SCRUB SEALS SEAMS SEATS SEEDS SEEKS SEEMS SEIZE SENSE SERUM SERVE SETUP SEVEN
SEWER SHACK SHADE SHAFT SHAKE SHALE SHAME SHANK SHAPE SHARD SHARE SHARK SHARP SHAVE SHAWL SHEAR
SHEDS SHEEP SHEER SHEET SHELF SHELL SHIFT SHINE SHINY SHIPS SHIRT SHOAL SHOCK SHOES SHONE SHOOK
SHOPS SHORE SHORT SHOTS SHOUT SHOVE SHOWN SHOWS SHRUB SHRUG SHUNT SIDES SIEGE SIGHS SIGHT SIGNS
SILKY SILLY SILOS SINCE SINEW SINGE SIREN SITES SIXTH SIXTY SIZES SKATE SKIES SKIFF SKILL SKIRT
SKULL SKUNK SLABS SLACK SLAIN SLANG SLANT SLASH SLATE SLAVE SLEDS SLEEK SLEEP SLEET SLICE SLICK
SLIDE SLIME SLING SLOPE SLOTH SLOTS SLUMP SMACK SMALL SMART SMASH SMEAR SMELL SMILE SMIRK SMOKE
SMOKY SNACK SNAIL SNAKE SNAPS SNARE SNARL SNEAK SNIFF SNIPE SNORE SNOUT SNOWY SOAPY SOBER SOCKS
SOGGY SOILS SOLAR SOLES SOLID SOLVE SONGS SONIC SORTS SOUND SOUPS SOURS SOWED SPACE SPADE SPANS
SPARE SPARK SPASM SPEAK SPEAR SPECK SPEED SPELL SPEND SPENT SPICE SPICY SPIED SPIES SPIKE SPILL
SPINE SPIRE SPITE SPLIT SPOIL SPOKE SPONGE SPOOL SPOON SPORE SPORT SPOTS SPOUT SPRAY SPUNK SPURN
SQUAD SQUAT STACK STAFF STAGE STAID STAIN STAIR STAKE STALE STALK STALL STAMP STAND STARE STARK
STARS START STASH STATE STAVE STAYS STEAD STEAK STEAL STEAM STEED STEEL STEEP STEER STEMS STEPS
STERN STICK STIFF STILL STILT STING STINK STINT STIRS STOCK STOIC STOKE STOLE STOMP STONE STOOD
STOOL STOOP STOPS STORE STORK STORM STORY STOUT STOVE STRAP STRAW STRAY STRIP STRUT STUCK STUDS
STUDY STUFF STUMP STUNG STUNT STYLE SUEDE SUGAR SUITE SUITS SULKY SUNNY SUPER SURGE SWAMP SWANS
SWARM SWATH SWEAR SWEAT SWEEP SWEET SWELL SWEPT SWIFT SWINE SWING SWIPE SWIRL SWISS SWORD SWORE
SWORN SYRUP TABLE TABOO TACIT TACKS TAILS TAKEN TAKES TALES TALKS TALLY TAMED TANGO TANKS TAPER
TAPES TARDY TARTS TASKS TASTE TAUNT TAWNY TAXES TEACH TEAMS TEARS TEASE TEETH TEMPO TEMPT TENDS
TENOR TENSE TENTH TENTS TERMS TESTS TEXTS THANK THEFT THEIR THEME THERE THESE THICK THIEF THIGH
THINE THING THINK THIRD THORN THOSE THREAD THREE THREW THROB THROW THUMB THUMP TIARA TIDAL TIDES
TIGER TIGHT TILES TIMER TIMES TIMID TINGE TIRED TITLE TOADS TOAST TODAY TOKEN TOMBS TONES TONGS
TOOLS TOOTH TOPIC TORCH TOTAL TOTEM TOUCH TOUGH TOURS TOWEL TOWER TOWNS TOXIC TRACE TRACK TRACT
TRADE TRAIL TRAIN TRAIT TRAMP TRAPS TRASH TRAWL TREAD TREAT TREES TREND TRIAL TRIBE TRICK TRIED
TRIES TRIMS TRIPS TROLL TROOP TROUT TRUCE TRUCK TRULY TRUMP TRUNK TRUST TRUTH TUBES TULIP TUMOR
TUNED TUNES TUNIC TURBO TURFS TWEAK TWEED TWICE TWIGS TWINE TWINS TWIST TYPES ULCER UNCLE UNDER
UNDID UNFIT UNION UNITE UNITS UNITY UNTIE UNTIL UPPER UPSET URBAN URGED URINE USAGE USHER USING
USUAL UTTER VAGUE VALID VALUE VALVE VAPOR VAULT VEINS VENOM VENTS VENUE VERBS VERGE VERSE VESTS
VIALS VICAR VIDEO VIEWS VIGIL VILLA VINES VINYL VIOLA VIPER VIRUS VISIT VISOR VISTA VITAL VIVID
VOCAL VODKA VOGUE VOICE VOILE VOTED VOTER VOTES VOWEL WAGER WAGES WAGON WAIST WAITS WAIVE WAKEN
WALLS WALTZ WANDS WANED WANTS WARDS WARES WARMS WARNS WARTS WASTE WATCH WATER WAVED WAVES WAXES
WEALTH WEARY WEAVE WEDGE WEEDS WEEKS WEEPS WEIGH WEIRD WELDS WELLS WHALE WHARF WHEAT WHEEL WHELP
WHERE WHICH WHIFF WHILE WHINE WHIRL WHISK WHITE WHOLE WHOSE WIDEN WIDER WIDOW WIDTH WIELD WILDS
WILLS WINCE WINDS WINDY WINES WINGS WIPED WIPES WIRED WIRES WISER WISPS WITCH WITTY WIVES WOKEN
WOMAN WOMEN WOODS WOODY WOOLY WORDS WORKS WORLD WORMS WORRY WORSE WORST WORTH WOUND WOVEN WRACK
WRATH WREAK WRECK WRIST WRITE WRONG WROTE YACHT YARDS YARNS YEARN YEARS YEAST YIELD YOKED YOUNG
YOURS YOUTH ZEBRA ZESTY ZONES""".split()
EX4 = """ACES ACHE ACRE AIDE AIMS AIRS AJAR ALLY ALSO ALTO AMID ANEW ANTS APEX APES APEX ARCH ARCS
ARID ARKS ARMS ATOM AUNT AUTO AVID AWED AXES AXIS BAIT BAKE BALD BALE BANE BARE BARK BARN BASK
BATS BEAD BEAK BEAM BEAN BEDS BEES BEET BENT BIAS BIBS BIDS BIKE BILE BINS BITE BITS BLED BLIP
BLOB BLOC BLOT BLUR BOAR BOLD BOLT BOND BONY BOOM BOON BORE BOTH BOUT BOWS BRAG BRAN BRAT BRAY
BREW BRIM BRIS BROW BUCK BUDS BUFF BUGS BULB BULL BUMP BUNK BUOY BURR BUST CABS CAFE CAGE CAKE
CANE CAPE CAPS CARS CARP CART CAVE CEDE CELL CENT CHAP CHAR CHEF CHEW CHIC CHIN CHOP CHUM CINE
CITE CLAD CLAM CLAN CLAP CLAW CLAY CLIP CLOG CLOT CLUE COAX COCK COIL COIN COLT COMB CONE COPS
CORD CORK CORN COTS COVE COWS COZY CRAB CRAG CRAM CRIB CROW CUBE CUBS CUED CUFF CULT CURB CURD
CURE CURL CUSP CYST DAMP DAMS DARE DARN DART DASH DAUB DAWN DAZE DEAF DEBT DECK DEED DEEM DEER
DELL DEMO DENS DENT DIME DINE DINS DIPS DIRE DIRT DISH DIVE DOCK DOES DOLL DOME DOOM DOTE DOVE
DOZE DRAB DRAG DRIP DUAL DUCK DUCT DUDE DUEL DUES DUET DULL DUMB DUNE DUSK DYED EASE EAVE EBBS
ECHO EDGY EELS EGGS EMIT ENDS ENVY EPIC EONS EWES EXAM EXIT FADE FANG FARE FAUN FAWN FEAT FERN
FEUD FIGS FILE FINS FIRS FIST FLAG FLAK FLAP FLAW FLEA FLED FLEE FLEW FLEX FLIP FLOP FLUE FLUX
FOAL FOAM FOES FOGS FOIL FOLD FOLK FOND FONT FORE FORK FOUL FOWL FRAY FRET FROG FROM FUME FUMY
FURS FUSE FUSS FUZZ GAGS GAIT GALA GALE GALL GAPE GAPS GARB GASH GAWK GAZE GEAR GEMS GENT GERM
GIGS GILD GILL GIRD GIST GLEE GLEN GLIB GLOW GLUE GLUM GNAT GNAW GOAD GOAT GONG GOOF GOWN GRAB
GRAD GRAM GRID GRIM GRIN GRIP GRIT GROW GRUB GULL GULP GUMS GURU GUSH GUST GUTS HACK HAIL HALE
HALT HAMS HARE HARP HASH HAUL HAWK HAYS HAZE HAZY HEAL HEAP HEED HEEL HEFT HEIR HEMS HENS HERB
HERD HEWN HIDE HIKE HILT HIND HINT HIVE HOAX HOBO HOES HOLE HOMY HONE HOOD HOOF HOOK HOOP HOOT
HOPS HORN HOSE HOST HUES HUGS HULL HUMP HUNG HUSH HUSK HUTS HYMN ICED ICON IDES IDLE IDLY IDOL
IMPS INKS INNS IONS IRIS IRKS ISLE ITCH JADE JAIL JAMS JARS JAWS JAZZ JEEP JEER JEST JETS JIBE
JIGS JILT JINX JOGS JOLT JOTS JUGS JUTE KALE KEEL KEEN KEGS KELP KEYS KILN KILT KITE KITS KNEE
KNIT KNOB KNOT LACE LACK LADS LAIR LAME LAMP LARD LASH LATH LAVA LAWN LAZY LEAF LEAK LEAN LEAP
LEEK LEER LENS LENT LEST LEWD LIAR LICE LICK LIDS LIEN LIEU LIMB LIME LIMP LINT LION LISP LOAF
LOAM LOBE LOCI LODE LOFT LOGS LOIN LOLL LONE LOOM LOON LOOP LOOT LOPE LORE LOUT LUGS LULL LUMP
LUNG LURE LURK LUSH LUTE LYNX MACE MAGI MAIM MAIZE MALT MANE MANY MAPS MARE MASH MASK MAST MATE
MATH MATS MAUL MAZE MEAD MEEK MELD MELT MEMO MEND MERE MESH MESS MICE MILD MILE MIME MINT MIRE
MIST MITE MITT MOAN MOAT MOCK MODE MOLD MOLE MOLT MOOR MOOT MOPS MOSS MOTH MOWN MUCK MUGS MULE
MULL MUSE MUSH MUSK MUST MUTE MUTT MYTH NAIL NAPE NAPS NEAT NEED NEON NEST NETS NEWT NIBS NICK
NINE NIPS NODE NODS NOOK NOON NOPE NORM NOSY NOUN NOVA NUDE NUNS OAKS OARS OATH OATS OBEY OBOE
ODDS ODES ODOR OGRE OILS OILY OKRA OMEN OMIT ONUS OOZE OPAL OPTS ORBS ORES OVAL OVEN OWED OWES
OWLS OXEN PACT PADS PAGE PAIL PALE PALS PANE PANG PANS PARE PART PAST PATS PAVE PAWN PAWS PEAK
PEAL PEAR PEAS PEAT PECK PEEK PEEL PEER PEGS PELT PENS PENT PERK PERT PEST PETS PEWS PIER PIES
PIGS PIKE PILE PILL PIMP PINE PING PINK PINS PINT PIPE PITH PITS PITY PLEA PLED PLOD PLOP PLOT
PLOW PLOY PLUM POCK PODS POEM POKE POLE POLL POLO POMP POND PONY POPS PORE PORK PORT POSE POSH
POST POSY POTS POUR POUT PRAM PRAY PREP PREY PRIG PRIM PROD PROM PROP PROW PUCK PUFF PUGS PUMA
PUMP PUNS PUNT PUNY PUPS PURE PURL PYRE QUAD QUIP QUIT QUIZ RACE RACK RAFT RAGE RAGS RAID RAIL
RAKE RAMP RAMS RANG RANT RAPS RAPT RARE RASH RASP RATE RATS RAVE RAYS RAZE READ REAM REAP REDO
REED REEF REEL REIN RELY REND RENT REST RIBS RICE RIDE RIFE RIFT RILE RIMS RIND RING RINK RIOT
RIPE RISE RISK RITE ROAD ROAM ROAR ROBE ROBS ROCK RODS ROIL ROLE ROLL ROMP ROOF ROOK ROOM ROOT
ROPE ROSE ROSY ROTE ROTS ROUT ROVE ROWS RUBS RUDE RUES RUFF RUGS RUIN RULE RUMP RUNG RUNS RUNT
RUSE RUSH RUST RUTS SACK SAGA SAGE SAGS SAIL SAKE SALE SALT SAME SAND SANE SANG SANK SAPS SASH
SAVE SAWS SCAB SCAM SCAN SCAR SEAL SEAM SEAR SEAS SEAT SECT SEED SEEK SEEM SEEN SEEP SEER SELF
SELL SEMI SEND SENT SETS SEWN SHAD SHAG SHAM SHED SHIN SHOD SHOO SHOT SHUN SHUT SICK SIFT SIGH
SIGN SILO SILT SINE SING SINK SIPS SIRE SITE SITS SIZE SKEW SKID SKIM SKIN SKIP SKIT SLAB SLAM
SLAP SLAT SLAY SLED SLEW SLID SLIM SLIP SLIT SLOB SLOG SLOP SLOT SLOW SLUG SLUM SLUR SMOG SMUG
SNAG SNAP SNIP SNOB SNUB SNUG SOAK SOAP SOAR SOBS SODA SOFA SOIL SOLD SOLE SOLO SOON SOOT SORE
SORT SOUL SOUP SOUR SOWN SPAN SPAR SPAT SPAY SPED SPIN SPIT SPUD SPUN SPUR STAB STAG STEM STEP
STEW STIR STOP STOW STUB STUD STUN STYE SUCH SUDS SUED SUES SUIT SULK SUMP SUMS SUNG SUNK SURE
SURF SWAB SWAG SWAM SWAN SWAP SWAT SWAY SWIG SWIM SWUM TABS TACK TACT TAGS TAIL TAKE TALC TALE
TALK TALL TAME TAMP TANG TANS TAPE TAPS TARE TARP TART TASK TAUT TAXI TEAK TEAL TEAM TEAR TEAS
TEEM TEEN TELL TEND TENT TERM TERN TEST THAW THEE THEM THEN THEY THIN THIS THUD THUG TICK TIDE
TIDY TIED TIER TIES TILE TILL TILT TIME TINE TINS TINT TINY TIPS TIRE TOAD TOES TOFU TOIL TOLD
TOLL TOMB TOME TONE TONS TOOL TOOT TORE TORN TOSS TOTE TOUR TOUT TOWN TOWS TOYS TRAM TRAP TRAY
TREE TREK TRIM TRIO TRIP TROD TROT TRUE TUBA TUBE TUBS TUCK TUFT TUGS TUNA TUNE TURF TURN TUSK
TWIG TWIN TWIT TYKE TYPE UNDO UNIT UPON URGE URNS USED USER USES VAIN VALE VANE VANS VASE VAST
VEAL VEER VEIL VEIN VEND VENT VERB VERY VEST VETO VIAL VIBE VICE VIED VIES VIEW VILE VINE VISA
VISE VOID VOLE VOLT VOTE VOWS WADE WAFT WAGE WAGS WAIF WAIL WAIT WAKE WALK WALL WAND WANE WANT
WARD WARE WARM WARN WARP WART WARY WASH WASP WAVE WAVY WAXY WEAK WEAN WEAR WEBS WEED WEEK WEEP
WEFT WELD WELL WELT WEND WENT WEPT WERE WEST WHAM WHAT WHEN WHET WHEY WHIM WHIP WHIR WHIT WHIZ
WHOA WHOM WICK WIDE WIFE WIGS WILD WILE WILL WILT WILY WIMP WIND WINE WING WINK WINS WIPE WIRE
WIRY WISE WISH WISP WITH WITS WOES WOKE WOLF WOMB WOOD WOOL WORD WORE WORK WORM WORN WOVE WRAP
WREN WRIT YAMS YANK YAPS YARD YARN YAWN YEAR YELL YELP YENS YETI YOGA YOKE YOLK YORE YOUR YOWL
YULE ZEAL ZERO ZEST ZINC ZONE ZOOM""".split()
EX3 = """ADO ADS AFT AHA AIL ALE ALP AMP ANT APE APT ARC ARK ASH ASP AWE AWL AXE AYE BAA BAN BAR BAT
BAY BEE BIB BID BIN BOA BOB BOG BOO BOP BOW BRA BUD BUG BUM BUN BUR BUS BYE CAB CAD CAM CAN CAP
CAW CHI COB COD COG CON COO COP COT COY CUB CUD CUE CUR DAB DAM DAB DEN DEW DIM DIN DIP DOC DOE
DON DOT DUB DUD DUE DUG DUO DYE EBB EEL EGO ELF ELK ELM EMU END EON ERA ERR EWE EYE FAD FAN FAR
FAX FED FEN FEZ FIB FIG FIN FIR FIT FIX FLU FLY FOE FOG FOP FOR FOX FRO FUR GAB GAG GAL GAP GAS
GEL GEM GEL GIG GIN GNU GOB GOO GUM GUT GYM HAG HAM HAS HAT HAY HEM HEN HER HEW HEX HID HIM HIP
HIS HIT HOB HOE HOG HOP HOT HOW HUB HUE HUG HUM HUT ICE ICY ILK ILL IMP INK INN ION IRE IRK IVY
JAB JAG JAM JAR JAW JAY JET JIB JIG JOB JOG JOT JOY JUG JUT KEG KEY KID KIN KIT LAB LAD LAG LAP
LAW LAX LAY LEA LED LEE LEG LET LID LIE LIP LIT LOB LOG LOP LOT LOW LUG LYE MAD MAN MAP MAR MAT
MAW MAY MEN MET MEW MID MIX MOB MOD MOM MOP MOW MUD MUG MUM NAB NAG NAP NAY NET NEW NIB NIL NIP
NIT NOD NOR NOT NOW NUB NUN NUT OAF OAK OAR OAT ODD ODE OFF OFT OHM OIL OLD ONE OPT ORB ORE OUR
OUT OWE OWL OWN PAD PAL PAN PAP PAR PAT PAW PAY PEA PEG PEN PEP PER PET PEW PIE PIG PIN PIT PLY
POD POI POP POT PRO PRY PUB PUG PUN PUP PUS PUT RAG RAM RAN RAP RAT RAW RAY RED REV RIB RID RIG
RIM RIP ROB ROD ROE ROT ROW RUB RUE RUG RUM RUN RUT RYE SAC SAD SAG SAP SAT SAW SAX SAY SEA SEE
SET SEW SHE SHY SIC SIN SIP SIR SIS SIT SIX SKI SKY SLY SOB SOD SOL SON SOP SOT SOW SOY SPA SPY
STY SUB SUE SUM SUN SUP TAB TAD TAG TAN TAP TAR TAX TEA TEE TEN THE THY TIC TIE TIN TIP TOE TOG
TON TOO TOP TOT TOW TOY TRY TUB TUG TUX TWO URN USE VAN VAT VET VEX VIA VIE VOW WAD WAG WAN WAR
WAS WAX WAY WEB WED WEE WET WHO WHY WIG WIN WIT WOE WOK WON WOO WOW WRY YAK YAM YAP YEA YES YET
YEW YIN YIP YON YOU ZAG ZAP ZIG ZIP ZOO""".split()
